language: php
dist: trusty

php:
    - 7.2

env:
    - DEPS=lowest
    - DEPS=latest

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: $SONAR_ORG
        token:
            secure: $SONAR_TOKEN

before_install:
    - travis_retry composer self-update

install:
    - if [[ $DEPS == 'latest' ]]; then travis_retry composer update -n --prefer-dist; fi
    - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update -n --prefer-lowest --prefer-stable; fi
    - stty cols 160 && composer show

script:
    - composer test-all

after_script:
    - if [[ $DEPS == 'latest' ]]; then bash <(curl -s https://codecov.io/bash); fi
    - |
        if [[ $DEPS == 'latest' ]]; then \
            sonar-scanner \
                -Dsonar.projectKey=$SONAR_PROJECT \
                -Dsonar.organization=$SONAR_ORG \
                -Dsonar.sources=src \
                -Dsonar.host.url=$SONAR_URL \
                -Dsonar.login=$SONAR_TOKEN \
                -Dsonar.exclusions=logs/**,vendor/** \
                -Dsonar.php.tests.reportPath=logs/phpunit/test-report.xml \
                -Dsonar.php.coverage.reportPaths=logs/phpunit/clover.xml \
        ; fi
